apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: replay-system
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: replay-system
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
